import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import {sanityClient,urlFor} from '../lib/sanity'
import styles from '../styles/Home.module.css'

export default function Home({data}) {
  const recipes=data.recipe; 
  return (
    <div className={styles.container}>
      <Head>
        <title>Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    </div>
  )
}

export function getStaticProps() {
  return {
    props: {
      data: {
        recipe: [{title: "pineapple"}],
      },
    },
  }
}