import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { sanityClient, urlFor } from "../lib/sanity";

const recipesQuery = `*[_type=="recipe"]{
  _id,
  name,
  slug,
  mainImage
}`;

export default function Home({ recipes }) {
	console.log(recipes);
	return (
		<div>
			<Head>
				<title>Recipes World🍔🥩</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>Welcome to the Recipes World🍔🥩</h1>
			<h4>{recipes.name}</h4>
			<ul className='recipe-list'>
				{recipes?.length > 0 &&
					recipes.map((recipe) => {
						return (
							<li key={recipe._id} className="recipe-card">
								<Link href={`/recipes/${recipe.slug.current}`}>
									<a>
										<img
											src={urlFor(recipe.mainImage).url()}
											alt={recipe.name}
										/>
										<span>{recipe.name}</span>
									</a>
								</Link>
							</li>
						);
					})}
			</ul>
		</div>
	);
}

export async function getStaticProps() {
	const recipes = await sanityClient.fetch(recipesQuery);
	return { props: { recipes } };
}
